{"version":3,"sources":["../../../src/server/wrap.js"],"names":["log","fn","catch","ex","console","error"],"mappings":"AAAA;;;AAGA,OAAOA,GAAP;AACA,gBAAe,UAACC,EAAD;AAAA,SACb;AAAA,WACEA,+BACGC,KADH,CACS,UAACC,EAAD,EAAQ;AACbC,cAAQC,KAAR,CAAcF,EAAd;AACD,KAHH,CADF;AAAA,GADa;AAAA,CAAf","file":"wrap.js","sourcesContent":["/* This is a function wrapper to correctly\n catch and handle uncaught exceptions in\n asynchronous code. */\nimport log from '../log'\nexport default (fn) =>\n  (...args) =>\n    fn(...args)\n      .catch((ex) => {\n        console.error(ex)\n      })\n"]}